# Declarative container images for the machines running ananke.
#
# Three shapes, because the images come three ways:
#
#   mkOverlayImage  a base image plus patches — Nix writes the Dockerfile
#   mkSourceImage   a source tree with its own Dockerfile
#   mkPulledImage   an upstream image, pinned to a digest
#
# The first two tag the image with the hash of what it was built from, so an
# image and the config describing it cannot drift: change a pin and the tag
# changes, which is what `mkImageService` looks for when deciding whether to
# build. The third needs no tag of its own — a digest already names exactly
# one image, and ananke passes the reference through to the runtime as-is.
{ pkgs, lib }:
let
  # Renders one overlay into its Dockerfile lines. The context copies `src`
  # to `overlays/<index>`, so no store path leaks into the build context.
  overlayLines = index: overlay:
    let ctx = "overlays/${toString index}"; in
    if overlay.install or false then
      # A patch directory. It lands at the path its `install.sh` hardcodes
      # as PATCHDIR, then runs. These are idempotent and fail loud, so a
      # patch that no longer applies stops the build rather than producing
      # a quietly unpatched image.
      [
        "COPY ${ctx} ${overlay.dest}"
        "RUN bash ${overlay.dest}/install.sh"
      ]
    else
      [ "COPY ${ctx} ${overlay.dest}" ];

  # Builds `context` if `tag` is not already present. The inspect keeps the
  # common case from even reading the context.
  buildIfMissing = { name, tag, context }: ''
    if docker image inspect ${tag} >/dev/null 2>&1; then
      echo "image ${name}: ${tag} already built"
    else
      echo "image ${name}: building ${tag}"
      docker build --tag ${tag} ${context}
    fi
  '';

  # The store hash of a path, which is what every locally-built tag is
  # versioned by.
  storeHash = path: lib.head (lib.splitString "-" (baseNameOf path));

  # A locally-built image exists only in Docker's store, so Podman cannot
  # pull it — it has to be handed across. Streamed rather than staged
  # through a file: these are gigabytes.
  loadIntoPodman = tag: ''
    if podman image exists ${tag}; then
      echo "image ${tag}: already in podman"
    else
      echo "image ${tag}: copying from docker into podman"
      docker save ${tag} | podman load
    fi
  '';
in
{
  # `base` is the image to build on, `overlays` the ordered list applied to
  # it. Each is `{ src; dest; install ? false; }` — `src` a path (file or
  # directory), `dest` where it lands in the image, and `install` whether to
  # run `dest/install.sh` afterwards.
  mkOverlayImage =
    { name
    , base
    , overlays ? [ ]
    }:
    let
      dockerfile = pkgs.writeText "${name}.Dockerfile" (
        lib.concatStringsSep "\n" (
          [
            "# Generated by common-all/container-images.nix. Do not edit on the host."
            "FROM ${base}"
          ]
          ++ lib.concatLists (lib.imap0 overlayLines overlays)
          ++ [ "" ]
        )
      );

      context = pkgs.runCommand "${name}-context" { } ''
        mkdir -p $out/overlays
        cp ${dockerfile} $out/Dockerfile
        ${lib.concatStringsSep "\n" (lib.imap0
          (index: overlay: ''
            cp -r ${overlay.src} $out/overlays/${toString index}
            chmod -R u+w $out/overlays/${toString index}
          '')
          overlays)}
      '';

      tag = "${name}:${storeHash context}";
    in
    {
      inherit name tag;
      buildCommand = buildIfMissing { inherit name tag context; };
      podmanCommand = loadIntoPodman tag;
    };

  # A source tree carrying its own Dockerfile — `src` is both the build
  # context and the recipe. Pin it with `fetchFromGitHub` rather than
  # pointing at a working tree, so the tag means something.
  mkSourceImage =
    { name
    , src
    }:
    let tag = "${name}:${storeHash src}"; in
    {
      inherit name tag;
      buildCommand = buildIfMissing { inherit name tag; context = src; };
      podmanCommand = loadIntoPodman tag;
    };

  # An upstream image pinned to a digest. The digest is the reference —
  # there is no local tag to keep in sync, and no way for the image to
  # change without this file changing.
  mkPulledImage =
    { name
    , ref
    , digest
    }:
    let tag = "${ref}@${digest}"; in
    {
      inherit name tag;
      buildCommand = ''
        if docker image inspect ${tag} >/dev/null 2>&1; then
          echo "image ${name}: ${tag} already present"
        else
          echo "image ${name}: pulling ${tag}"
          docker pull ${tag}
        fi
      '';
      # Podman can fetch a digest from the registry itself; nothing has to
      # cross from Docker's store.
      podmanCommand = ''
        if podman image exists ${tag}; then
          echo "image ${name}: ${tag} already in podman"
        else
          echo "image ${name}: pulling ${tag} into podman"
          podman pull ${tag}
        fi
      '';
    };

  # A oneshot that makes every image present before ananke wants them.
  # Ordered before ananke rather than required by it: a build that fails
  # should leave ananke running its other services, with the affected ones
  # failing to start and saying why.
  #
  # `podmanImages` also need to be in Podman's store, which does not share
  # Docker's. Set `user` when that store is a rootless one.
  mkImageService =
    { images
    , podmanImages ? [ ]
    , user ? null
    , after ? [ "docker.service" ]
    , requires ? [ "docker.service" ]
    }:
    {
      description = "Build the container images ananke serves";
      inherit after requires;
      wantedBy = [ "multi-user.target" ];
      before = [ "ananke.service" ];
      path = [ pkgs.docker ] ++ lib.optional (podmanImages != [ ]) pkgs.podman;
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        # A cold run pulls multi-gigabyte bases and, for source images,
        # compiles them.
        TimeoutStartSec = "3h";
      } // lib.optionalAttrs (user != null) { User = user; };
      script = lib.concatStringsSep "\n" (
        [ "set -euo pipefail" ]
        ++ map (image: image.buildCommand) images
        ++ map (image: image.podmanCommand) podmanImages
      );
    };
}
